openapi: "3.0.3"
info:
  title: 車両情報連携システム
  version: "0.0.1"
servers:
  - url: https://api.server.test/v1
paths:
  /trackBySIP:
    $ref: "./paths/trackBySIP.yaml"
  /vehicleIncidentInfo:
    $ref: "./paths/vehicleIncidentInfo.yaml"
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: apiKey
      in: header
    Authorization:
      type: http
      scheme: bearer
      description: アクセストークン発行APIで発行したアクセストークン
