routes:
  required:
  - dataModelType
  - attribute
  type: object
  description: 経路探索
  properties:
    dataModelType:
      type: string
      description: データモデルタイプ
      enum:
        - test1
        - test2
      example: test1
    attribute:
        type: object
        description: データモデル要素
        required:
          - routeId
          - points
          - etaSec
          - distanceMeters
        properties:
          routeId:
            type: string
            format: uuid 
            description: ルートID
            example: "78aa302c-1600-44b3-a331-e4659c0b28a1"
          points:
            type: array
            description: ルートの開始から終了までの走行ポイント配列
            minItems: 0
            maxItems: 100 #要確認
            items:
              type: object
              properties:
                location:
                  type: object
                  description: 走行ポイント位置情報
                  required:
                    - lat
                    - lng
                  properties:
                    lat:
                      type: number
                      description: 緯度
                      format: double
                      minimum: -90
                      maximum: 90
                      example: 35.6242681254456
                    lng:
                      type: number
                      description: 経度
                      format: double
                      minimum: -180
                      maximum: 180
                      example: 139.74258640456
          etaSec:
            type: number
            description: ルートの走行の予想時間[s]
            minimum: # 設定ない
            maximum: # 設定ない
            example: 60
          distanceMeters:
            type: number
            description: ルートの走行距離[m]
            minimum: # 設定ない
            maximum: # 設定ない
            example: 600
          
